# Generated by Django 4.0.3 on 2022-03-23 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='filters.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_filter',
            field=models.ManyToManyField(to='filters.productfilter'),
        ),
        migrations.AddField(
            model_name='product',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_material', to='filters.rawmaterial'),
        ),
        migrations.AddField(
            model_name='product',
            name='taste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taste', to='filters.taste'),
        ),
    ]
