# Generated by Django 4.0.3 on 2022-03-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_category_product_product_filter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='text',
        ),
        migrations.AddField(
            model_name='productreview',
            name='content',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
