# Generated by Django 4.0.3 on 2022-03-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
        ('product', '0003_remove_productreview_text_productreview_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_material', to='filters.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='product',
            name='taste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taste', to='filters.taste'),
        ),
    ]
