# Generated by Django 4.0.3 on 2022-03-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_average_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rate',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
