# Generated by Django 4.0.3 on 2022-03-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_average_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rate',
            field=models.DecimalField(decimal_places=1, default='0.0', max_digits=3, null=True),
        ),
    ]
